[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = "liepue2osuxh"
  CONTENTFUL_ACCESS_TOKEN = "7EAPNKvEOiRi8j0O3rkswBO2hpJoAm7f-hX2fUZxi4w"
  CONTENTFUL_PREVIEW_ACCESS_TOKEN = "YR2NHdQDA06epj2lHJf5Ytm8nCkEEkkCQ4UKz9UXLco"
